/**
 * GENERATED BY `pnpm video:audio`. Do not edit by hand.
 *
 * Every number here was measured off a real file: line positions from ffprobe, loudness read
 * back off the finished WAV with ffmpeg loudnorm. See ./timings.ts for why this is committed
 * and the WAVs it describes are not.
 */
import type { PostAudio } from "./timings";

export const AUDIO: Record<string, PostAudio> = {
  "reframe-001": {
    id: "reframe-001",
    voice: "af_heart",
    file: "audio/mix/reframe-001.wav",
    voEndSeconds: 4.392,
    voEndFrame: 132,
    seconds: 11.5,
    frames: 345,
    lines: [
      { written: "no this isn't a dating app", spoken: "no this isn't a dating app.", startSeconds: 0.2, endSeconds: 1.757, startFrame: 6, endFrame: 53 },
      { written: "it's for finding people to actually play with", spoken: "it's for finding people to actually play with.", startSeconds: 2.024, endSeconds: 4.392, startFrame: 61, endFrame: 132 },
    ],
    loudness: { integratedLufs: -14.3, truePeakDb: -1.2, lra: 2.3 },
  },
};
