/**
 * Regenerates supabase/seed/seed.sql from the JSON catalogs in supabase/seed/.
 * Run with: pnpm tsx scripts/build-seed-sql.ts
 *
 * games.json / shows.json stay the single source of truth for the catalog data;
 * this script is the only thing that hand-writes seed.sql, so the two never drift.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const seedDir = join(__dirname, "..", "supabase", "seed");

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

const games: string[] = JSON.parse(readFileSync(join(seedDir, "games.json"), "utf8"));
const shows: Array<{ name: string; category: "show" | "movie" | "anime" }> = JSON.parse(
  readFileSync(join(seedDir, "shows.json"), "utf8"),
);

const gameValues = games.map((name) => `  (${sqlString(name)}, false)`).join(",\n");
const showValues = shows
  .map(({ name, category }) => `  (${sqlString(name)}, ${sqlString(category)}, false)`)
  .join(",\n");

const sql = `-- AUTO-GENERATED by scripts/build-seed-sql.ts from games.json / shows.json.
-- Do not edit by hand — edit the JSON files and rerun the script instead.
-- Applied automatically by \`supabase db reset\` (see supabase/config.toml [db.seed]).

insert into public.games (name, is_custom)
values
${gameValues}
on conflict (lower(name)) do nothing;

insert into public.shows (name, category, is_custom)
values
${showValues}
on conflict (lower(name)) do nothing;
`;

writeFileSync(join(seedDir, "seed.sql"), sql);
console.log(`Wrote supabase/seed/seed.sql (${games.length} games, ${shows.length} shows).`);
